---
title: "Data cleaning"
date: today
format:
  html:
    embed-resources: true
     
---

```{r setup}
#| message: false
#| output: false

# install XLConnect
# remotes::install_github("miraisolutions/xlconnect")

# install Java: https://www.timsanteford.com/posts/how-to-install-java-on-macos-using-homebrew/

# src: https://stackoverflow.com/a/54827489

# necessary for XLConnect
options(java.parameters = c("-XX:+UseConcMarkSweepGC", "-Xmx8192m")) # set Java limit
gc() # garbage collection (for use here and after each change in the excel workbook object)

pacman::p_load("janitor",
               "readr",
               "dplyr",
               "lubridate",
               "stringr",
               "labelled",
               "gtsummary",
               "XLConnect",
               "sf",
               "rdeck")

theme_gtsummary_compact()
```

```{r source-functions}
# source(here::here("R", "helper_functions.R"))
```

```{r import}
#| output: false

# HR data ----
file <- here::here("data_raw", "ppmc_ee_20251219.xlsx")
file_annotated <- here::here("data_raw", "ppmc_ee_20251219_annotated.xlsx")
password <- keyring::key_get("ppmc-ee")

wb <- loadWorkbook(filename = file_annotated, password = password)

# List available sheets (to confirm sheet names)
sheets <- getSheets(wb)
# print(sheets)  # Output: e.g., "ALL EE ", "DB_Pension"
 
# Read a specific sheet (e.g., "ALL EE")
data_all_ee <- readWorksheet(wb, sheet = "ALL EE ", startRow = 1, header = TRUE) |> clean_names()
data_db_pension <- readWorksheet(wb, sheet = "DB_Pension", startRow = 1, header = TRUE) |> clean_names()
data_dc_403b <- readWorksheet(wb, sheet = "DC_403b Retirement", startRow = 1, header = TRUE) |> clean_names()
data_retirement_loans <- readWorksheet(wb, sheet = "Retirement Loans", startRow = 1, header = TRUE)
# # --- hidden data
# data_loa_wc_nosal <- readWorksheet(wb, sheet = "LOA_WC_No Sal Data", startRow = 1, header = TRUE) |> clean_names()
# data_roster <- readWorksheet(wb, sheet = "Roster", startRow = 1, header = TRUE) |> clean_names()
# # --- hidden data
gc()

# zip codes ----
boxDrive <- here::here("/Users/scanelon/Library/CloudStorage/Box-Box", "Green-Geobirth R01", "3. Data-related (nonPHI)", "Data_Spatial")

zips <-
  st_read(paste(boxDrive,
                "data_intermediate",
                "spatial_layers",
                "Open Data Philly",
                "City_Boundaries",
                "Zipcodes_Poly.gpkg",
                sep = "/"))
```

<!--## Overview-->

```{r, results="asis"}
#| eval: false
#| column: screen-inset-right

# summarytools::view(
#   summarytools::dfSummary(data_all_ee,
#                           col.widths = c(100, 100, 200, 100, 100, 100, 100))
#   )

summarytools::dfSummary(
  data_all_ee,
  plain.ascii  = FALSE, 
  style        = "grid", 
  graph.magnif = 0.82, 
  varnumbers   = FALSE,
  valid.col    = FALSE,
  tmp.img.dir  = "/tmp"
)
```


```{r add-labels}
data_all_ee <-
  data_all_ee |> 
  set_variable_labels(
    fte = "FTE",
    annual_salary = "Annual salary",
    race_ethnicity = "Race/ethnicity",
    gender = "Gender",
    job_category = "Job category",
    sub_category = "Job sub category",
    work_location = "Work location",
    work_zip_code = "Work zip code",
    state = "State",
    zip_code = "Employee zip code"
  )

data_ee_trim <-
  data_all_ee |> 
  select(ee_id, fte, annual_salary, race_ethnicity, gender,
         job_category, sub_category, work_location, work_zip_code,
         state, zip_code)
```


## Salary category


```{r}
data_ee_trim <-
  data_ee_trim |>
  mutate(annual_salary_category = case_when(
    annual_salary < 62000 ~ "Less than 62k",
    annual_salary >= 62000 & annual_salary < 100000 ~ "62k-100k",
    annual_salary >= 100000 & annual_salary < 150000 ~ "100k-150k",
    annual_salary >= 150000 & annual_salary < 200000 ~ "150k-200k",
    annual_salary >= 200000 ~ "More than 200k"
  )) |> 
  mutate(annual_salary_category = factor(annual_salary_category,
                                         levels = c("Less than 62k",
                                                    "62k-100k",
                                                    "100k-150k",
                                                    "150k-200k",
                                                    "More than 200k"))) |> 
  set_variable_labels(annual_salary_category = "Annual salary category")
```

```{r}
#| column: page-right
tbl_summary(data_ee_trim,
            include = c(race_ethnicity,
                        fte,
                        gender,
                        # job_category,
                        annual_salary_category),
            by = annual_salary_category,
            type = all_continuous() ~ "continuous2",
            statistic = all_continuous() ~ c(
              "{mean} ({sd})",
              "{median}",
              "{min}-{max}"
            ),
            sort = list(c(gender) ~ "alphanumeric")) |> 
  add_overall() |> 
  bold_labels() |> 
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |>
  as_gt() %>%
  gt::cols_width(
    label ~ px(220),
    everything() ~ px(110)
  ) |> 
  gt::tab_header(title = "Employee Salary") |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```

## Job category and subcategory

```{r}
#| column: page-right
#| output: false

# DO NOT USE: sub_category and job_category do not nest appropriately ----
# tbl_job <-
#   tbl_strata_nested_stack(
#   data_ee_trim,
#   strata = job_category,
#   .tbl_fun = ~ .x |>
#     tbl_summary(#data = data_ee_trim,
#                 include = c(#job_category,
#                             sub_category,
#                             annual_salary_category),
#                 by = annual_salary_category,
#                 percent = "column") |> 
#     # add_overall() |>
#     # replace 0 (0%) and 0 (NA %) with em dash
#     # src: https://github.com/ddsjoberg/gtsummary/issues/2153#issuecomment-2664253147
#     modify_table_body(
#     ~ .x |>
#       mutate(across(all_stat_cols(), ~ ifelse(. %in% c("0 (0%)" ,"0 (NA%)", "NA (NA, NA)"), NA, .)))
#   ) |>
#   modify_missing_symbol(
#     symbol = "---", # converts to an em-dash
#     columns = all_stat_cols(),
#     rows =
#       (var_type %in% c("continuous", "dichotomous") & row_type == "label") |
#       (var_type %in% c("continuous2", "categorical") & row_type == "level")
#   ),
#   row_header = "{strata}, n = {n}, N = {N}"
# ) |>
#   modify_header(all_stat_cols() ~ "**{level}**") |>
#   modify_bold(columns = "label", rows = tbl_indent_id1 > 0) |>
#   modify_caption("Job category/subcategory by salary")
# tbl_job
# ----

summary_job_income <- 
  data_ee_trim |> 
  group_by(job_category) |> 
  mutate(n_job_category = n_distinct(ee_id)) |> 
  group_by(job_category, n_job_category, sub_category) |> 
  mutate(n_sub_category = n_distinct(ee_id),
         prop_sub_category = n_sub_category/n_job_category) |> 
  group_by(job_category, n_job_category, sub_category, 
           n_sub_category, prop_sub_category, annual_salary_category) |> 
  summarize(n_salary_category = n_distinct(ee_id),
            prop_salary_category = n_salary_category/n_job_category) |>
  unique() |> 
  ungroup() |> 
  # convert to uppercase so sorting alphabetically ignores case
  arrange(str_to_upper(job_category)) |> 
  tidyr::pivot_wider(names_from = annual_salary_category,
                     values_from = c(n_salary_category, prop_salary_category),
                     names_glue = "{.value}_{annual_salary_category}") |> 
  clean_names()
```

```{r}
#| column: page-right
# gt ----
summary_job_income |>
  group_by(job_category) |> 
  gt::gt() |> 
  gt::cols_hide(n_job_category) |> 
  gt::fmt_percent(
    columns = tidyselect::contains("prop"),
    decimals = 1,
    pattern = "({x})"
  ) |> 
  gt::summary_rows(
    groups = everything(),
    columns = tidyselect::starts_with("n_"),
    fns = list("Total, job category" ~ sum(., na.rm = TRUE)),
    fmt = ~ fmt_number(., decimals = 0),
    side = "top"
  ) |>
  gt::summary_rows(
    groups = everything(),
    columns = tidyselect::starts_with("prop_"),
    fns = list("Total, job category" ~ sum(., na.rm = TRUE)),
    fmt = ~ fmt_percent(., decimals = 1, pattern = "({x})"),
    side = "top"
  ) |>
  gt::grand_summary_rows(
    columns = tidyselect::starts_with("n_"),
    fns = list("Total, N" ~ sum(., na.rm = TRUE)),
    fmt = ~ fmt_number(., decimals = 0, use_seps = FALSE)
  ) |>
  gt::tab_spanner(
    columns = c(n_sub_category, prop_sub_category),
    label = gt::md("Overall")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("less_than_62k"),
    label = gt::md("Less than 62k")
  ) |> 
    gt::tab_spanner(
    columns = tidyselect::contains("62k_100k"),
    label = gt::md("62k-100k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("100k_150k"),
    label = gt::md("100k-150k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("150k_200k"),
    label = gt::md("150k-200k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("more_than_200k"),
    label = gt::md("More than 200k")
  ) |> 
  gt::sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "---"
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = list(gt::cells_row_groups(),
                     gt::cells_column_spanners(),
                     gt::cells_column_labels(sub_category))
  ) |> 
  gt::cols_label(
    starts_with("n_") ~ "n",
    starts_with("prop_") ~ "(%)"
  ) |>
  gt::cols_width(
    sub_category ~ px(260),
    everything() ~ px(80)
  ) |> 
  gt::tab_header(
    title = "Job category / sub category by salary category"
  ) |> 
  gt::opt_vertical_padding(scale = 0.2) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```

## FTE

```{r}
fte_403b <-
  data_dc_403b |> 
  left_join(data_ee_trim,
            by = c("employment_id" = "ee_id"))

fte_pension <-
  data_db_pension |> 
  left_join(data_ee_trim,
            by = c("employment_id" = "ee_id"))

tbl_fte_403b <-
  fte_403b |> 
  tbl_summary(include = c(fte),
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c(
                "{min}",
                "{max}"
              ),
              by = work_type_description) #|> 
  # modify_caption("FTE among 403b employees")

tbl_fte_pension <-
  fte_pension |> 
  tbl_summary(include = c(fte),
              type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c(
                "{min}",
                "{max}"
              ),
              by = work_type_description) #|> 
  # modify_caption("FTE among pension employees")

tbl_stack(tbls = list(tbl_fte_403b, tbl_fte_pension),
          group_header = c("403b", "Pension")) |> 
  modify_source_note('"Unknown" represents employees excluded from shared dataset') |>
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |>
  as_gt() |> 
  gt::cols_width(
    label ~ px(90),
    everything() ~ px(80)
  ) |> 
  gt::tab_header(title = "FTE by Work Description") |> 
  gt::opt_vertical_padding(scale = 0.25) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```


## Retirement plans

### 403b

```{r}
#| column: page-right

data_ee_pension_403b <-
  data_ee_trim |> 
  mutate(flag_pension = if_else(ee_id %in% data_db_pension$employment_id, "Yes", "No"),
         flag_pension = factor(flag_pension, levels = c("Yes", "No")),
         flag_403b = if_else(ee_id %in% data_dc_403b$employment_id, "Yes", "No"),
         flag_403b = factor(flag_403b, levels = c("Yes", "No"))) |> 
  set_variable_labels(flag_pension = "Pension plan",
                      flag_403b = "403b Plan")

data_ee_pension_403b |> 
  tbl_summary(include = c(flag_pension,
                          annual_salary_category,
                          race_ethnicity,
                          gender,
                          job_category),
              by = flag_403b,
              percent = "column",
              sort = list(job_category ~ "frequency")) |> 
  add_overall() |>
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |>
  as_gt() |> 
  gt::cols_width(label ~ px(220),
                 everything() ~ px(80)) |> 
  gt::tab_header(title = "Employees with 403b retirement plan") |> 
  gt::opt_vertical_padding(scale = 0.25) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
  
```

### Pension

```{r}
#| column: page-right

data_ee_pension_403b |> 
  tbl_summary(include = c(flag_403b,
                          annual_salary_category,
                          race_ethnicity,
                          gender,
                          job_category),
              by = flag_pension,
              percent = "column",
              sort = list(job_category ~ "frequency")) |> 
  add_overall() |>
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |>
  as_gt() |> 
  gt::cols_width(label ~ px(220),
                 everything() ~ px(80)) |> 
  gt::tab_header(title = "Employees with pension plan") |> 
  gt::opt_vertical_padding(scale = 0.25) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```

## Retirement loans

```{r}
#| column: page-right

summary_retirement_loans <-
  data_retirement_loans |> 
  clean_names() |> 
  group_by(employment_id) |> 
  mutate(n_loans = n()) |> 
  set_variable_labels(description = "Loan description")

data_ee_loans <-
  data_ee_trim |> 
  left_join(summary_retirement_loans, by = c("ee_id" = "employment_id"))

data_ee_loans |> 
  tbl_summary(include = c(n_loans,
                          description,
                          annual_salary_category,
                          race_ethnicity,
                          gender,
                          job_category),
              by = n_loans,
              sort = list(description ~ "alphanumeric")) |> 
  add_overall() |>
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |>
  as_gt() |> 
  gt::cols_width(label ~ px(220),
                 everything() ~ px(80)) |> 
  gt::tab_header(title = "Number of retirement loans") |>
  gt::opt_vertical_padding(scale = 0.25) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```

## Employee location

### Work vs. home zip codes

```{r}
#| column: page-right

data_ee_location <-
  data_ee_trim |>
  mutate(work_zip_code_short = str_remove(work_zip_code, pattern = "\\-[0-9]{4}"),
         zip_code_short = str_remove(zip_code, pattern = "\\-[0-9]{4}")) |> 
  mutate(flag_work_and_home = if_else(work_zip_code_short == zip_code_short, "Yes", "No"),
         flag_work_and_home = factor(flag_work_and_home,
                                     levels = c("Yes", "No"))) |> 
  set_variable_labels(flag_work_and_home = "Same zip for work and home",
                      work_zip_code_short = "Work zip code",
                      zip_code_short = "Home zip code")

data_ee_location |> 
  tbl_summary(include = c(flag_work_and_home,
                          annual_salary_category,
                          race_ethnicity,
                          gender,
                          job_category),
              by = flag_work_and_home) |> 
  add_overall() |>
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |> 
  as_gt() |>
  gt::cols_width(label ~ px(220),
                 everything() ~ px(80)) |> 
  gt::tab_header("Employees work in the zip code they live in") |> 
  gt::opt_vertical_padding(scale = 0.2) |> 
  gt::opt_table_font(font = "Avenir",
                     stack = "rounded-sans")
  
```

```{r}
#| output: false

summary_zip_codes <-
  data_ee_location |> 
  group_by(zip_code_short) |> 
  mutate(n_zip_code = n_distinct(ee_id),
         n_zip_code = as.numeric(n_zip_code)) |> 
  group_by(zip_code_short, n_zip_code, annual_salary_category) |> 
  summarize(n_salary_category = n_distinct(ee_id),
            prop_salary_category = n_salary_category/n_zip_code) |> 
  arrange(desc(n_zip_code)) |> 
  unique() |> 
  ungroup() |> 
  mutate(n_zip_code_cat = cut(
      n_zip_code,
      breaks = seq(0, 100, by = 20),
      labels = c("0-20", "20-40", "40-60", "60-80", "80-100"),
      include.lowest = TRUE,
      right = TRUE),
      .after = n_zip_code
      ) |> 
  set_variable_labels(zip_code_short = "Zip code",
                      n_zip_code = "Number in zip code",
                      n_zip_code_cat = "Number in zip code")
```

### Home zip code & salary

```{r}
#| column: page-right

data_ee_location |> 
  tbl_summary(include = c(zip_code_short,
                          annual_salary_category),
              by = annual_salary_category,
              sort = zip_code_short ~ "frequency") |> 
  add_overall() |> 
  modify_header(all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p)}%)") |> 
  as_gt() |>
  gt::cols_width(label ~ px(100),
                 everything() ~ px(80)) |> 
  gt::tab_header("Employee home zip code and salary categories") |> 
  gt::opt_vertical_padding(scale = 0.25) |> 
  gt::opt_table_font(font = "Avenir",
                     stack = "rounded-sans") |> 
  gt::opt_interactive(page_size_default = 20,
                      use_compact_mode = TRUE,
                      use_search = TRUE)

sf_zips <-
  zips |>
  select(CODE) |> 
  left_join(summary_zip_codes, 
            by = c("CODE" = "zip_code_short"), 
            keep = TRUE) |> 
  select(-CODE)

# mapgl::maplibre_view(
#   data = sf_zips,
#   column = "n_zip_code"
# )

```

### Map

```{r}
#| output: false
mapbox_access_token()
```


```{r}
#| column: page-right

map_zip_codes <-
  rdeck(map_style = mapbox_light(),
      initial_view_state = view_state(
        center = c(-75.14873, 39.99692),
        zoom = 9.5
      )) |> 
  # add unseen schools ----
  add_polygon_layer(
    data = sf_zips, 
    name = "Number of employees\nin zip code",
    get_polygon = geom,
    get_line_color = "#FFFFFF",
    get_line_width = 0.25,
    line_width_units = "pixels",
    stroked = TRUE,
    filled = TRUE,
    # get_fill_color = scale_color_linear(
    #   col = "n_zip_code",
    #   palette = scales::viridis_pal()),
    get_fill_color =  scale_color_category(
      col = "n_zip_code_cat",
      palette = scales::viridis_pal(),
      col_label = "Number in zip code"
    ),
    line_width_scale = 5,
    # line_width_min_pixels = 5,
    # line_width_max_pixels = 30,
    auto_highlight = TRUE,
    highlight_color = "#e69138", # ffd966 yellow
    visible = TRUE,
    pickable = TRUE,
    tooltip = c(zip_code_short, n_zip_code)
  )
map_zip_codes

htmlwidgets::saveWidget(
  widget = map_zip_codes,
  title = "Number of employees in zip code",
  file = here::here("data", "map_zip_codes.html"),
  selfcontained = TRUE
) 

```


## Work location

```{r}
#| column: page-right
#| output: false
#| 
summary_work_location <- 
  data_ee_trim |> 
  group_by(work_location) |> 
  mutate(n_work_location = n_distinct(ee_id),
         mean_fte = mean(fte),
         sd_fte = sd(fte),
         min_fte = min(fte),
         max_fte = max(fte)) |> 
  group_by(work_location, n_work_location, 
           mean_fte, sd_fte, min_fte, max_fte, annual_salary_category) |> 
  summarize(n_salary_category = n_distinct(ee_id),
            prop_salary_category = n_salary_category/n_work_location) |> 
  # a more granular approach
  # summarize(n_salary_category = n_distinct(ee_id),
  #           prop_salary_category = n_salary_category/n_work_location,
  #           mean_fte = mean(fte),
  #           sd_fte = sd(fte),
  #           min_fte = min(fte),
  #           max_fte = max(fte)) |> 
  unique() |> 
  ungroup() |> 
  # convert to uppercase so sorting alphabetically ignores case
  arrange(str_to_upper(work_location)) |> 
  tidyr::pivot_wider(names_from = annual_salary_category,
                     values_from = c(n_salary_category, prop_salary_category),
                     # for the more granular approach:
                     # values_from = c(n_salary_category, prop_salary_category,
                     #                 mean_fte, sd_fte, min_fte, max_fte),
                     names_glue = "{.value}_{annual_salary_category}") |> 
  clean_names() |> 
  arrange(desc(n_work_location))
```

```{r}
#| column: page-right
# gt ----
summary_work_location |>
  # group_by(work_location) |>
  gt::gt() |> 
  # gt::cols_hide(n_work_location) |>
  gt::fmt_percent(
    columns = tidyselect::contains("prop"),
    decimals = 1,
    pattern = "({x})"
  ) |> 
  gt::fmt_number(
    columns = tidyselect::contains(c("mean", "min", "max"))
  ) |> 
  gt::fmt_number(
    columns = tidyselect::contains("sd"),
    pattern = "({x})"
  ) |> 
  gt::cols_merge(
    columns = c(mean_fte, sd_fte)
  ) |>
  gt::cols_merge_range(
    col_begin = min_fte,
    col_end = max_fte
  ) |> 
  # more granular approach ----
  # gt::cols_merge(
  #   columns = c(mean_fte_less_than_62k, sd_fte_less_than_62k)
  # ) |> 
  # gt::cols_merge(
  #   columns = c(mean_fte_62k_100k, sd_fte_62k_100k)
  # ) |> 
  # gt::cols_merge(
  #   columns = c(mean_fte_100k_150k, sd_fte_100k_150k)
  # ) |> 
  # gt::cols_merge(
  #   columns = c(mean_fte_150k_200k, sd_fte_150k_200k)
  # ) |> 
  # gt::cols_merge(
  #   columns = c(mean_fte_more_than_200k, sd_fte_more_than_200k)
  # ) |> 
  # gt::cols_merge_range(
  #   col_begin = min_fte_less_than_62k,
  #   col_end = max_fte_less_than_62k
  # ) |> 
  # gt::cols_merge_range(
  #   col_begin = min_fte_62k_100k,
  #   col_end = max_fte_62k_100k
  # ) |> 
  # gt::cols_merge_range(
  #   col_begin = min_fte_100k_150k,
  #   col_end = max_fte_100k_150k
  # ) |> 
  # gt::cols_merge_range(
  #   col_begin = min_fte_150k_200k,
  #   col_end = max_fte_150k_200k
  # ) |> 
  # gt::cols_merge_range(
  #   col_begin = min_fte_more_than_200k,
  #   col_end = max_fte_more_than_200k
  # ) |> 
  # ----
  # gt::summary_rows(
  #   groups = everything(),
  #   columns = tidyselect::starts_with("n_"),
  #   fns = list("Total, work location" ~ sum(., na.rm = TRUE)),
  #   fmt = ~ fmt_number(., decimals = 0),
  #   side = "top"
  # ) |>
  # gt::summary_rows(
  #   groups = everything(),
  #   columns = tidyselect::starts_with("prop_"),
  #   fns = list("Total, work location" ~ sum(., na.rm = TRUE)),
  #   fmt = ~ fmt_percent(., decimals = 1, pattern = "({x})"),
  #   side = "top"
  # ) #|>
  gt::grand_summary_rows(
    columns = tidyselect::starts_with("n_"),
    fns = list("Total, N" ~ sum(., na.rm = TRUE)),
    fmt = ~ fmt_number(., decimals = 0, use_seps = FALSE)
  ) |>
  gt::tab_spanner(
    columns = c(n_work_location, mean_fte, sd_fte, min_fte, max_fte),
    label = gt::md("Overall")
  ) |>
  gt::tab_spanner(
    columns = tidyselect::contains("less_than_62k"),
    label = gt::md("Less than 62k")
  ) |> 
    gt::tab_spanner(
    columns = tidyselect::contains("62k_100k"),
    label = gt::md("62k-100k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("100k_150k"),
    label = gt::md("100k-150k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("150k_200k"),
    label = gt::md("150k-200k")
  ) |> 
  gt::tab_spanner(
    columns = tidyselect::contains("more_than_200k"),
    label = gt::md("More than 200k")
  ) |> 
  gt::sub_missing(
    columns = everything(),
    rows = everything(),
    missing_text = "---"
  ) |> 
  gt::tab_style(
    style = gt::cell_text(weight = "bold"),
    locations = list(gt::cells_row_groups(),
                     gt::cells_column_spanners(),
                     gt::cells_column_labels(work_location)
                     )
  ) |> 
  gt::cols_label(
    starts_with("n_") ~ "n",
    starts_with("prop_") ~ "(%)",
    starts_with("mean_fte") ~ "Mean FTE (SD)",
    starts_with("min_fte") ~ "FTE Range"
  ) |>
  gt::cols_width(
    work_location ~ px(120),
    starts_with(c("mean_", "min_")) ~ px(120),
    everything() ~ px(80)
  ) |> 
  gt::tab_header(
    title = "Work location by salary category"
  ) |> 
  gt::opt_vertical_padding(scale = 0.2) |> 
  gt::opt_table_font(font = "Avenir", 
                     stack = "rounded-sans")
```
